version: '3.8'

services:
  # 核心服务：Aggregator
  aggregator:
    # 用户直接从 Docker Hub 拉取您构建好的镜像
    image: devinglaw/aggregator:latest
    container_name: aggregator
    restart: unless-stopped
    # working_dir 不再需要，Dockerfile 已定义

    # 关键：用户只需关心将自己的配置文件和数据目录挂载进来
    volumes:
      # 1. 挂载用户的配置文件
      - ./config.aggregator.json:/aggregator/subscribe/config/config.json:ro
      # 2. 挂载用户的数据输出目录
      - ./data:/aggregator/data
      # 3. (可选) 挂载用户的自定义脚本目录
      - ./scripts:/aggregator/subscribe/scripts:ro

    # 关键：用户通过 .env 文件安全地传入自己的敏感信息
    env_file:
      - .env.aggregator
      
    # 注意：entrypoint 部分已完全移除！
    # 容器将自动使用镜像内置的 entrypoint.sh 脚本，这正是我们想要的。

  # Watchtower 服务保持不变，用于自动更新 aggregator 镜像
  watchtower:
    # watchtower 服务部分保持不变
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
    command: ""
